Repository Borewit/musicbrainz-api, pull requests merged in 2024-08, with the labels that each got.

#953 Switch Eslint to Biome
  .c8rc.json
  .eslintrc.json
  .github/workflows/nodejs-ci.yml
  biome.jsonc
  lib/coverartarchive-api.ts
  lib/digest-auth.ts
  lib/musicbrainz-api.ts
  lib/musicbrainz.types.ts
  package.json
  test/test-musicbrainz-api.ts
  yarn.lock
Labels: DevOps

#895 Update README.md for Release Group Cover Art
  README.md
Labels: documentation

#964 Update to ECMAScript 2020
  README.md
  tsconfig.json
Labels: technical-debt

#965 Add sponsorship information
  README.md
Labels: documentation

#967 Fix dependencies
  .github/workflows/nodejs-ci.yml
  package.json
  yarn.lock
Labels: bug

#970 Improve covert art examples
  README.md
Labels: documentation

#972 Add bundle size
  README.md
Labels: documentation

#973 CI: Minor changes to readability
  .github/workflows/nodejs-ci.yml
Labels: DevOps

#968 Replace "got" HTTP-client with fetch API, improving browser compatibility
  biome.jsonc
  lib/coverartarchive-api.ts
  lib/digest-auth.ts
  lib/httpClient.ts
  lib/musicbrainz-api.ts
  package.json
  test/test-musicbrainz-api.ts
  yarn.lock
Labels: enhancement
